language: python
python:
  - 3.3
  - 2.7
before_install:
 - mkdir -p $HOME/.cache/pip/wheels
 # build wheel only if none present
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels numpy
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels scipy
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels pandas
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels matplotlib
 # now install from it
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels numpy
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels scipy
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels pandas
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels matplotlib
install:
  - python setup.py install
  - pip install coveralls
script:
  - python setup.py test
  - python -m coverage run --source=./mupit -m unittest discover
after_success:
  - coveralls
