language: r
sudo: required
warnings_are_errors: true
r_packages:
 - covr
 - testthat
r_github_packages:
 - jeremymcrae/publishedDeNovos
r_binary_packages:
 - testthat
after_success:
 - Rscript -e 'covr::coveralls()'
