language: r
sudo: required
warnings_are_errors: true
r_packages:
 - covr
 - testthat
r_github_packages:
 - jeremymcrae/publishedDeNovos
 # install the latest version of qqman, which isn't available on CRAN yet
 - stephenturner/qqman
r_binary_packages:
 - testthat
after_success:
 - Rscript -e 'covr::coveralls()'
